CREATE TABLE usuario (

    id INTEGER NOT NULL AUTO_INCREMENT,
    nome VARCHAR(60) NOT NULL,
    email VARCHAR(60) NOT NULL UNIQUE,
    senha VARCHAR(100) NOT NULL,
    isAtivo BOOLEAN NOT NULL,
    perfil VARCHAR(50) NOT NULL,

    PRIMARY KEY (id)
);